# https://taskfile.dev

version: "3"

tasks:
  install:
    cmds:
      - pip install --upgrade pip && pip install -r requirements.txt

  format:
    cmds:
      - black *.py

  lint:
    cmds:
      - pylint *.py

  test:
    cmds:
      - echo "Testing..."
    silent: true

  deploy:
    cmds:
      - echo "Deploying..."
    silent: true

  all:
    cmds:
      - task install
      - task format
      - task lint
      - task test
      - task deploy
    silent: true
