name: Python Micro Service CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          task install
      - name: Lint with pylint
        run: |
          task lint
      - name: Format with black
        run: |
          task format
